c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
vc:                            # [win]
  - 14                         # [win]
python:                        # [win]
  - 3.7                        # [win]
python_impl:                   # [win]
  - cpython                    # [win]
numpy:                         # [win]
  - 1.17                       # [win]
