travis:
  secure:
    BINSTAR_TOKEN: T9mRQrqO8i4RKr2yF2vvU0JLue910L9k8iJCA+vPfKf7w+eRghp2ZOhgL/dE44HwS/eqsZfIQWyvzumh1/+Ho3Y2o3D8h7veCtDxvLKrt3LlV1K/QGGXAPw6yM6x3vKetdeX4lPBKdp5S1hEqwthRzZhDc1R1OacLxpQn4xCEB3zzMFja65V/DdE4dsS5JHEA/bb+tGXloD2dxJB9wzs70/bAnXKxnG9F4OCCyuHmAzTxWI0qDPUSy5Vv6pnSGVu4662b6WrYuu/mkaKkcC0dTwhBm4oTzpEu06eXQRy+hKVbT0Ass/QcY3Lzq9dS6Z5/Br/aslblEpL/gBqoGmco5BYEcl0ix6nHci/FD6TlXrTcJtykHA0fTJv2c70QyqyPJ5vJIsx88MzFCH+dGn9MiOI4/72vjX57wM/VvFuS2JdJqUTqUn1Bp3yqeCeedTxqTvt2AqUloZGi0DC0sWOansVe2CQzDrB+B2XoYZrvBXeyFysYYMwYifokLgi49gwLuiqjo9kRsT7VrjrO9IPQ6q9537XSBICaQOPfF+epDtz2xVLs5NBP4Y6+8NjOvYl4doLj5b8cmAnH73mru0PjBkEqF6tsC9STBEZ6rVABf38fif0juQBbvhp5gtro9M1U4c1eHnSYqXjYRUdT5/gtYKaSznIW368WHfbVoVGI5o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
